"""empty message

Revision ID: 5ed7a995f31a
Revises: 0fe615ff41bd
Create Date: 2023-10-03 22:47:49.780323

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ed7a995f31a"
down_revision: Union[str, None] = "0fe615ff41bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = postgresql.ENUM("admin", "user", name="role", create_type=True)
    role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("users", sa.Column("role", role_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")

    role_enum = postgresql.ENUM("admin", "user", name="role")
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
